package com.app.Utilities;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

import java.io.FileOutputStream;
import java.time.LocalDate;
import java.util.Date;

@Component
public class PDFgenerator {


    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);

    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

    public void PDFgenerator(String filePath, Integer userLoginId , String email, Long contact,
                             Integer BusId, LocalDate journeyDate , String source, String destination,
                             Integer noOfSeatsBooked,String reservationStatus,Integer fare, String reservationType ) {
        try {
            Document document = new Document();

            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            addMetaData(document);
            addTitleAndTable(document, userLoginId , email, contact,
                    BusId, journeyDate , source, destination,
                    noOfSeatsBooked, reservationStatus, fare, reservationType);

            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    private static void addTitleAndTable(Document document,Integer userLoginId , String email, Long contact,
                                         Integer BusId, LocalDate journeyDate , String source, String destination,
                                         Integer noOfSeatsBooked,String reservationStatus,Integer fare, String reservationType)
            throws DocumentException {
        Paragraph preface = new Paragraph();

        preface.add(new Paragraph("Bus booking details", catFont));


        preface.add(new Paragraph(
                "Report generated by: " + "Bus Reservation Company" + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));

        document.add(preface);
        document.add(Chunk.NEWLINE);
        document.add(Chunk.NEWLINE);

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Passenger Details"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        c1.setColspan(2);
        table.addCell(c1);

        table.addCell("ReservationStatus");
        table.addCell(reservationStatus);
        table.addCell("Passenger Id");
        table.addCell(String.valueOf(userLoginId));
        table.addCell("Passenger Email");
        table.addCell(email);
        table.addCell("Phone Number");
        table.addCell(String.valueOf(contact));


        document.add(table);

        PdfPTable table1 = new PdfPTable(2);
        table1.setWidthPercentage(100);

        PdfPCell c2 = new PdfPCell(new Phrase("Bus Details"));
        c2.setHorizontalAlignment(Element.ALIGN_CENTER);
        c2.setColspan(2);
        table1.addCell(c2);

        table1.addCell("Bus Id");
        table1.addCell(String.valueOf(BusId));
        table1.addCell("JourneyDate");
        table1.addCell(String.valueOf(journeyDate));
        table1.addCell("ReservationType");
        table1.addCell(reservationType);
        table1.addCell("Source");
        table1.addCell(source);
        table1.addCell("Destination");
        table1.addCell(destination);
        table1.addCell("NoOfSeatsBooked");
        table1.addCell(String.valueOf(noOfSeatsBooked));
        table1.addCell("Fare");
        table1.addCell(String.valueOf(fare));

        document.add(table1);

        document.close();
    }


}
